feat: implement text inspector and case converter tool
rusconn/DevToysWeb pull request #3
Opened 2024-05-14 16:08 UTC by ershisan99

## Description: 

- Implements text inspector and case converter tool
- Updates Readme.md's todo section with this change 

## Preview

Sentence case
<img width="1440" alt="image" src="https://github.com/rusconn/DevToysWeb/assets/95695678/66123bf8-bec2-46e8-8486-c7a935ad77ab">

Contsant case
<img width="1440" alt="Screenshot 2024-05-14 at 18 06 02" src="https://github.com/rusconn/DevToysWeb/assets/95695678/f31316b5-3602-42c8-b854-c5abbbdb0b61">

Original case with emoji, showcases the correct characters and bytes counters values
<img width="1440" alt="Screenshot 2024-05-14 at 18 06 30" src="https://github.com/rusconn/DevToysWeb/assets/95695678/47065c47-24f5-4d21-a46f-992798cc661c">

2024-05-16 08:31 UTC, ershisan99 commented
@rusconn Hi, do you mind having a look at the pr please? :-)

2024-09-20 07:13 UTC, rusconn commented
@ershisan99 Sorry for being late. I'll check it out.

2024-09-20 07:25 UTC, rusconn commented on README.md
> +- [(Shallow routing) updating search params causes server code to rerun.](https://github.com/vercel/next.js/issues/49668)
This must be nested. I'm using React context instead of query parameters to avoid re-running server code 😀

2024-09-20 07:26 UTC, rusconn commented on app/text/inspector/page.tsx
> +  );
memoizing 👍

2024-09-20 07:27 UTC, rusconn commented on app/text/inspector/page.tsx
> +      <PageSection className="min-h-[200px] flex-1" title="Information">
Maybe `min-h-[200px]` is not necessary?

2024-09-20 07:28 UTC, rusconn commented on app/text/inspector/page.tsx
> +          <Textarea value={output} onChange={noOp} rows={10} readOnly />
I want to know why `onChange={noOp}` is necessary!

2024-09-20 07:36 UTC, rusconn commented on lib/base.ts
Sorry for the bad file name 🙇. This file is for number-base-conversion. I would like the text-tools lib to be placed somewhere else!

2024-09-20 07:47 UTC, rusconn commented on lib/text.ts
> +  const words = text.split(/\s+/);
I think we need to take care of the punctuation. How about using `/[\s\p{P}]+/u`?🤔
The `\p{P}` represents punctuation.
The `u` flag enables various Unicode-related features: <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode>

2024-09-20 07:48 UTC, rusconn commented on lib/text.ts
> +  return [...new Intl.Segmenter().segment(text)].length;
Nice feature! 😁

2024-09-20 08:18 UTC, rusconn commented on lib/text.ts
> +  return new Blob([text]).size;
One possible approach is to use `new TextEncoder().encode(text).length`.
I think it is easy to understand that the text is converted to UTF-8.
What do you think? 😃

2024-09-20 08:24 UTC, rusconn commented on lib/text.ts
> +      return text;
I would like to suggest using `throw new Error(mode satisfies never);`.
This is type safe for case exhaustiveness!

2024-09-20 08:29 UTC, rusconn requested changes
Thank you for your contribution!
Please check my comments 😃

2024-10-24 11:48 UTC, merged